"""Rebuild config/fno200.csv from live NSE fnolist() + known lot sizes + sector map."""
from nsepython import fnolist

LOT_SIZES = {
    "NIFTY": 75, "BANKNIFTY": 30, "FINNIFTY": 65, "MIDCPNIFTY": 120, "NIFTYNXT50": 25,
    "RELIANCE": 250, "HDFCBANK": 550, "ICICIBANK": 700, "TCS": 150, "INFY": 400,
    "SBIN": 1500, "AXISBANK": 1200, "KOTAKBANK": 400, "HINDUNILVR": 300, "BHARTIARTL": 475,
    "ITC": 3200, "MARUTI": 25, "TITAN": 175, "BAJFINANCE": 125, "ASIANPAINT": 300,
    "LT": 175, "NTPC": 2250, "HCLTECH": 350, "WIPRO": 1500, "ADANIENT": 400,
    "SUNPHARMA": 700, "M&M": 350, "TATASTEEL": 5500, "ULTRACEMCO": 100, "NESTLEIND": 50,
    "BAJAJFINSV": 125, "POWERGRID": 4500, "COALINDIA": 2100, "ONGC": 1925, "BPCL": 1800,
    "HDFCLIFE": 1100, "DRREDDY": 125, "GRASIM": 475, "TECHM": 600, "DIVISLAB": 200,
    "ADANIPORTS": 1250, "TATAMOTORS": 1425, "JSWSTEEL": 1350, "INDUSINDBK": 500,
    "SBILIFE": 750, "CIPLA": 650, "APOLLOHOSP": 125, "EICHERMOT": 50, "TATACONSUM": 900,
    "BRITANNIA": 100, "BAJAJ-AUTO": 75, "HEROMOTOCO": 150, "SHRIRAMFIN": 150,
    "ICICIPRULI": 1500, "TRENT": 350, "CHOLAFIN": 750, "ADANIGREEN": 500, "ADANIPOWER": 1150,
    "ABB": 150, "AMBUJACEM": 2000, "BANKBARODA": 5400, "BEL": 3700, "BHEL": 3500,
    "BIOCON": 1100, "BOSCHLTD": 30, "CANBK": 3000, "COCHINSHIP": 500, "COLPAL": 350,
    "CONCOR": 500, "CUMMINSIND": 300, "DABUR": 1250, "DLF": 1650, "ESCORTS": 200,
    "ETERNAL": 2300, "FEDERALBNK": 5000, "GAIL": 3825, "GODREJCP": 500, "HAVELLS": 500,
    "HINDCOPPER": 2700, "HINDPETRO": 1300, "HINDZINC": 2150, "IDFCFIRSTB": 5000,
    "INDHOTEL": 1400, "INDUSTOWER": 1400, "IRFC": 3000, "IEX": 3750, "IRCTC": 875,
    "JIOFIN": 3750, "JSL": 1500, "JUBLFOOD": 1250, "KALYANKJIL": 1000, "LICI": 700,
    "LTIM": 150, "LUPIN": 425, "MAZDOCK": 125, "MFSL": 650, "MPHASIS": 200,
    "MUTHOOTFIN": 350, "NMDC": 4500, "NYKAA": 3000, "OBEROIRLTY": 425, "OFSS": 100,
    "PAGEIND": 15, "PATANJALI": 300, "PEL": 350, "PERSISTENT": 100, "PIDILITIND": 250,
    "PNB": 8000, "POLYCAB": 125, "PVRINOX": 408, "RECLTD": 2100, "SAIL": 4300,
    "SHREECEM": 25, "SIEMENS": 125, "SRF": 250, "SUZLON": 5000, "TATACHEM": 500,
    "TATACOMM": 250, "TATAPOWER": 2700, "TIINDIA": 300, "TORNTPHARM": 125,
    "TORNTPOWER": 250, "TVSMOTOR": 350, "UBL": 400, "UNITDSPR": 400, "UPL": 1300,
    "VEDL": 2000, "VOLTAS": 500, "WAAREEENER": 150, "ZOMATO": 4500, "ZYDUSLIFE": 700,
    "AARTIIND": 500, "ABCAPITAL": 5000, "ABFRL": 2800, "ACC": 500, "ADANIENSOL": 400,
    "ALKEM": 75, "APARINDS": 150, "APLAPOLLO": 400, "ATGL": 3000, "AUROPHARMA": 650,
    "BALKRISIND": 250, "BANDHANBNK": 5000, "BERGEPAINT": 1100, "BHARATFORG": 750,
    "BSE": 250, "CAMS": 250, "CANFINHOME": 1250, "CGPOWER": 2000, "CLEAN": 700,
    "COFORGE": 150, "CROMPTON": 2000, "DALBHARAT": 400, "DEEPAKFERT": 500,
    "DEVYANI": 3500, "DIXON": 75, "DMART": 400, "GLENMARK": 700, "GNFC": 600,
    "GPIL": 500, "GRINDWELL": 300, "HDFCAMC": 200, "IDFC": 6000, "IIFL": 1200,
    "INDIANB": 1200, "INDIGO": 300, "JKCEMENT": 200, "KPITTECH": 500, "KFINTECH": 600,
    "LICHSGFIN": 1000, "LALPATHLAB": 300, "LAURUSLABS": 1500, "LTTS": 150, "LUXIND": 150,
    "MANAPPURAM": 3000, "MAXHEALTH": 700, "MCX": 200, "METROPOLIS": 300, "MOTHERSON": 4000,
    "MTAR": 200, "NATIONALUM": 4750, "NBCC": 5500, "NCLIND": 750, "NHPC": 6750,
    "NLCINDIA": 3000, "NOCIL": 1600, "PAYTM": 2000, "PIIND": 200, "PNBHOUSING": 750,
    "POLICYBZR": 1000, "PRESTIGE": 700, "RADICO": 500, "RAYMOND": 200, "RITES": 700,
    "RVNL": 2500, "SAFARI": 200, "SJVN": 5000, "SKFINDIA": 150, "SONACOMS": 1000,
    "STARHEALTH": 1000, "SUPREME": 375, "SWIGGY": 2600, "TANLA": 350, "TATAELXSI": 100,
    "TATAINVEST": 250, "TITAGARH": 700, "TRIDENT": 8000, "UCOBANK": 5000, "VBL": 500,
    "VGUARD": 2000, "VINATIORGA": 300, "WHIRLPOOL": 150, "WOCKPHARMA": 650,
    "YESBANK": 20000, "ZEEL": 3000, "HINDALCO": 1050, "GODREJPROP": 750,
    "ASHOKLEY": 3000, "MARICO": 1200, "GRASIM": 475, "L&TFH": 7000,
    "NAM-INDIA": 1500, "EARLYWEL": 1500, "JUBLINEFOO": 1250,
    # Previously unknown — patched
    "360ONE": 600, "AMBER": 200, "ANGELONE": 250, "ASTRAL": 500, "AUBANK": 500,
    "BAJAJHLDNG": 18, "BANKINDIA": 1600, "BDL": 300, "BLUESTARCO": 375,
    "CDSL": 500, "DELHIVERY": 1100, "EXIDEIND": 1300, "FORCEMOT": 75,
    "FORTIS": 1500, "GMRAIRPORT": 13500, "GODFRYPHLP": 300, "HAL": 150,
    "HUDCO": 2000, "HYUNDAI": 50, "ICICIGI": 400, "IDEA": 70000,
    "INOXWIND": 1200, "IOC": 3500, "IREDA": 2000, "JINDALSTEL": 625,
    "JSWENERGY": 1500, "KAYNES": 75, "KEI": 250, "LODHA": 500,
    "LTF": 5000, "LTM": 500, "MANKIND": 375, "MOTILALOFS": 150,
    "NAUKRI": 150, "NUVAMA": 150, "OIL": 875, "PETRONET": 3000,
    "PFC": 2250, "PGEL": 1000, "PHOENIXLTD": 875, "POWERINDIA": 150,
    "PPLPHARMA": 1500, "PREMIERENE": 3000, "RBLBANK": 2600, "SAMMAANCAP": 2000,
    "SBICARD": 800, "SOLARINDS": 75, "SUPREMEIND": 300, "TATATECH": 550,
    "TMPV": 500, "UNIONBANK": 3000, "UNOMINDA": 2400, "VMM": 500,
}

SECTOR_MAP = {
    "TCS": "IT", "INFY": "IT", "HCLTECH": "IT", "WIPRO": "IT", "TECHM": "IT",
    "LTIM": "IT", "MPHASIS": "IT", "PERSISTENT": "IT", "COFORGE": "IT", "LTTS": "IT",
    "KPITTECH": "IT", "OFSS": "IT", "TATAELXSI": "IT", "TANLA": "IT",
    "HDFCBANK": "BANK", "ICICIBANK": "BANK", "SBIN": "BANK", "AXISBANK": "BANK",
    "KOTAKBANK": "BANK", "INDUSINDBK": "BANK", "FEDERALBNK": "BANK",
    "BANDHANBNK": "BANK", "PNB": "BANK", "CANBK": "BANK", "BANKBARODA": "BANK",
    "IDFCFIRSTB": "BANK", "INDIANB": "BANK", "UCOBANK": "BANK", "YESBANK": "BANK",
    "IDFC": "BANK",
    "SUNPHARMA": "PHARMA", "DRREDDY": "PHARMA", "CIPLA": "PHARMA", "DIVISLAB": "PHARMA",
    "BIOCON": "PHARMA", "LUPIN": "PHARMA", "AUROPHARMA": "PHARMA", "ALKEM": "PHARMA",
    "GLENMARK": "PHARMA", "LALPATHLAB": "PHARMA", "METROPOLIS": "PHARMA",
    "ZYDUSLIFE": "PHARMA", "LAURUSLABS": "PHARMA", "WOCKPHARMA": "PHARMA",
    "MARUTI": "AUTO", "TATAMOTORS": "AUTO", "M&M": "AUTO", "BAJAJ-AUTO": "AUTO",
    "HEROMOTOCO": "AUTO", "EICHERMOT": "AUTO", "TVSMOTOR": "AUTO", "ASHOKLEY": "AUTO",
    "BALKRISIND": "AUTO", "ESCORTS": "AUTO", "MOTHERSON": "AUTO", "BHARATFORG": "AUTO",
    "TIINDIA": "AUTO", "SONACOMS": "AUTO",
    "HINDUNILVR": "FMCG", "ITC": "FMCG", "NESTLEIND": "FMCG", "BRITANNIA": "FMCG",
    "DABUR": "FMCG", "COLPAL": "FMCG", "MARICO": "FMCG", "GODREJCP": "FMCG",
    "TATACONSUM": "FMCG", "UBL": "FMCG", "VBL": "FMCG", "RADICO": "FMCG",
    "UNITDSPR": "FMCG",
    "TATASTEEL": "METAL", "JSWSTEEL": "METAL", "SAIL": "METAL", "HINDALCO": "METAL",
    "VEDL": "METAL", "NMDC": "METAL", "COALINDIA": "METAL", "HINDCOPPER": "METAL",
    "HINDPETRO": "METAL", "NATIONALUM": "METAL", "HINDZINC": "METAL", "JSL": "METAL",
    "GPIL": "METAL",
    "RELIANCE": "ENERGY", "ONGC": "ENERGY", "BPCL": "ENERGY", "GAIL": "ENERGY",
    "ADANIGREEN": "ENERGY", "ADANIPOWER": "ENERGY", "TATAPOWER": "ENERGY",
    "NTPC": "ENERGY", "POWERGRID": "ENERGY", "NHPC": "ENERGY", "SJVN": "ENERGY",
    "NLCINDIA": "ENERGY", "TORNTPOWER": "ENERGY", "ADANIENSOL": "ENERGY",
    "ATGL": "ENERGY", "RECLTD": "ENERGY", "SUZLON": "ENERGY", "WAAREEENER": "ENERGY",
    # Previously unknown sectors — patched
    "360ONE": "NBFC", "AMBER": "CONSUMER", "ANGELONE": "EXCHANGE",
    "ASTRAL": "INFRA", "AUBANK": "BANK", "BAJAJHLDNG": "HOLDING",
    "BANKINDIA": "BANK", "BDL": "DEFENCE", "BLUESTARCO": "CONSUMER",
    "CDSL": "EXCHANGE", "DELHIVERY": "LOGISTICS", "EXIDEIND": "AUTO",
    "FORCEMOT": "AUTO", "FORTIS": "HEALTHCARE", "GMRAIRPORT": "INFRA",
    "GODFRYPHLP": "FMCG", "GRASIM": "CEMENT", "HAL": "DEFENCE",
    "HUDCO": "NBFC", "HYUNDAI": "AUTO", "ICICIGI": "INSURANCE",
    "IDEA": "TELECOM", "INOXWIND": "ENERGY", "IOC": "ENERGY",
    "IREDA": "ENERGY", "JINDALSTEL": "METAL", "JSWENERGY": "ENERGY",
    "KAYNES": "IT", "KEI": "CABLES", "LODHA": "REALTY", "LTF": "NBFC",
    "LTM": "INFRA", "MANKIND": "PHARMA", "MOTILALOFS": "NBFC",
    "NAUKRI": "IT", "NUVAMA": "NBFC", "OIL": "ENERGY", "PATANJALI": "FMCG",
    "PETRONET": "ENERGY", "PFC": "ENERGY", "PGEL": "CABLES",
    "PHOENIXLTD": "REALTY", "POWERINDIA": "ENERGY", "PPLPHARMA": "PHARMA",
    "PREMIERENE": "ENERGY", "RBLBANK": "BANK", "SAMMAANCAP": "NBFC",
    "SBICARD": "NBFC", "SOLARINDS": "ENERGY", "SUPREMEIND": "INFRA",
    "TATATECH": "IT", "TMPV": "AUTO", "TORNTPHARM": "PHARMA",
    "UNIONBANK": "BANK", "UNOMINDA": "AUTO", "UPL": "CHEMICALS", "VMM": "UNKNOWN",
    "BAJFINANCE": "NBFC", "BAJAJFINSV": "NBFC", "SHRIRAMFIN": "NBFC",
    "CHOLAFIN": "NBFC", "MUTHOOTFIN": "NBFC", "JIOFIN": "NBFC", "L&TFH": "NBFC",
    "LICHSGFIN": "NBFC", "PNBHOUSING": "NBFC", "ABCAPITAL": "NBFC",
    "CANFINHOME": "NBFC", "IIFL": "NBFC", "MANAPPURAM": "NBFC", "MFSL": "NBFC",
    "NAM-INDIA": "NBFC", "HDFCAMC": "NBFC",
    "HDFCLIFE": "INSURANCE", "SBILIFE": "INSURANCE", "ICICIPRULI": "INSURANCE",
    "LICI": "INSURANCE", "STARHEALTH": "INSURANCE", "MAXHEALTH": "INSURANCE",
    "POLICYBZR": "INSURANCE",
    "LT": "INFRA", "BHEL": "INFRA", "SIEMENS": "INFRA", "ABB": "INFRA",
    "ADANIPORTS": "INFRA", "CONCOR": "INFRA", "IRFC": "INFRA", "RVNL": "INFRA",
    "NBCC": "INFRA", "INDUSTOWER": "INFRA", "BEL": "INFRA", "MAZDOCK": "INFRA",
    "TITAGARH": "INFRA", "COCHINSHIP": "INFRA", "CGPOWER": "INFRA",
    "GRINDWELL": "INFRA",
    "DLF": "REALTY", "OBEROIRLTY": "REALTY", "PRESTIGE": "REALTY",
    "GODREJPROP": "REALTY",
    "TITAN": "CONSUMER", "TRENT": "CONSUMER", "NYKAA": "CONSUMER", "DMART": "CONSUMER",
    "JUBLFOOD": "CONSUMER", "DEVYANI": "CONSUMER", "PVRINOX": "CONSUMER",
    "PAGEIND": "CONSUMER", "KALYANKJIL": "CONSUMER", "LUXIND": "CONSUMER",
    "RAYMOND": "CONSUMER", "SAFARI": "CONSUMER", "WHIRLPOOL": "CONSUMER",
    "BHARTIARTL": "TELECOM", "TATACOMM": "TELECOM",
    "AMBUJACEM": "CEMENT", "ACC": "CEMENT", "ULTRACEMCO": "CEMENT",
    "SHREECEM": "CEMENT", "DALBHARAT": "CEMENT", "JKCEMENT": "CEMENT",
    "NCLIND": "CEMENT",
    "ASIANPAINT": "PAINTS", "BERGEPAINT": "PAINTS",
    "PIDILITIND": "CHEMICALS", "DEEPAKFERT": "CHEMICALS", "SRF": "CHEMICALS",
    "GNFC": "CHEMICALS", "AARTIIND": "CHEMICALS", "VINATIORGA": "CHEMICALS",
    "NOCIL": "CHEMICALS",
    "POLYCAB": "CABLES", "HAVELLS": "CABLES", "CROMPTON": "CABLES", "VGUARD": "CABLES",
    "BSE": "EXCHANGE", "MCX": "EXCHANGE", "IEX": "EXCHANGE",
    "APOLLOHOSP": "HEALTHCARE", "INDHOTEL": "HOTELS",
    "IRCTC": "TRANSPORT", "INDIGO": "AVIATION",
    "ZOMATO": "INTERNET", "ETERNAL": "INTERNET", "SWIGGY": "INTERNET",
    "PAYTM": "FINTECH",
    "TATAINVEST": "HOLDING", "ADANIENT": "HOLDING",
    "BOSCHLTD": "AUTO", "CUMMINSIND": "INFRA", "SKFINDIA": "INFRA",
    "DIXON": "CONSUMER", "APARINDS": "AUTO", "APLAPOLLO": "METAL",
    "PIIND": "CHEMICALS", "CLEAN": "PHARMA", "SCHILPMED": "PHARMA",
    "TRIDENT": "TEXTILE", "RAYMOND": "TEXTILE", "ABFRL": "TEXTILE",
    "MTAR": "INFRA", "RITES": "INFRA", "SUPREME": "INFRA",
    "VOLTAS": "CONSUMER", "KFINTECH": "FINTECH", "CAMS": "FINTECH",
    "EARLYWEL": "FMCG", "JUBLINEFOO": "CONSUMER",
}

INDICES = {"NIFTY", "NIFTYIT", "BANKNIFTY", "FINNIFTY", "MIDCPNIFTY", "NIFTYNXT50", "SENSEX", "BANKEX"}

stocks = fnolist()
equities = [s for s in stocks if s not in INDICES]
print(f"F&O equities from NSE: {len(equities)}")
print(f"IBULLSLTD present: {'IBULLSLTD' in equities}")

rows = []
unknown_lot = []
unknown_sector = []
for sym in sorted(equities):
    lot = LOT_SIZES.get(sym, 0)
    if lot == 0:
        unknown_lot.append(sym)
        lot = 500
    sector = SECTOR_MAP.get(sym, "UNKNOWN")
    if sector == "UNKNOWN":
        unknown_sector.append(sym)
    rows.append(f"{sym},{sector},{lot}")

print(f"Unknown lot sizes (defaulted 500): {len(unknown_lot)} -> {unknown_lot}")
print(f"Unknown sectors: {len(unknown_sector)} -> {unknown_sector}")

with open("config/fno200.csv", "w") as f:
    f.write("symbol,sector,lot_size\n")
    f.write("\n".join(rows) + "\n")

print(f"\nWrote {len(rows)} rows to config/fno200.csv")
